### ISSUE TITLE
Installation is not working

### ISSUE THREAD

**Issue by anantgrafix** [driesvints/blade-icons#57] opened 2020-06-18 09:22 UTC
In BladeIconsServiceProvider.php line 34:

  Trying to access array offset on value of type null

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by driesvints** [comment] 2020-06-18 10:21
We'll need more info than this. Can you please post the full steps to reproduce? I'm currently using the package in production without issues.

**Comment by HowardF** [comment] 2020-06-18 13:03
Exactly same issue here. Occured when "artisan package:discover --ansi" is run after installation. 
On MacOS (Catalina) with PHP 7.4.7 and latest Laravel.

**Comment by driesvints** [comment] 2020-06-18 13:10
Again: we'll need much more info here. At the moment I can install it perfectly fine. Please share a test repo where this is happening.

**Comment by HowardF** [comment] 2020-06-18 16:59
Got it working after doing config:clear, cache:clear, view:clear etc. Thanks.

**Comment by driesvints** [comment] 2020-06-18 18:41
Gotcha. @anantgrafix feel free to reply when you have more info.

**Comment by rompetomp** [comment] 2020-06-21 15:29
@driesvints FWIW I also had this issue. This happens when the config has been cached, and then composer require is called with this application. Because I don't cache my config in my development environment, but I do on my Forge server, I had this issue when deploying through forge.

**Comment by driesvints** [comment] 2020-06-21 15:36
@rompetomp thanks for noting. I see what's going on here. Because we're calling the config while registering the service provider it's not always available. I'm sure I set up like this for a specific reason (I think testing) but I need to check in thoroughly soon why.

**Comment by papalardo** [comment] 2020-06-22 01:38
I did have some problem. 
Then I `remove package` and run: 

```bash
composer remove blade-ui-kit/blade-icons
php artisan config:clear
php artisan view:clear
php artisan cache:clear
composer require blade-ui-kit/blade-icons
```

And try `install again` and Works.

**Comment by driesvints** [comment] 2020-06-27 14:04
This should be fixed with https://github.com/blade-ui-kit/blade-icons/commit/5e69d6075e2e2a4204d172d36a6864b32f9014dc. I'll tag a new release in a bit.

In general I want to note that it's always a good idea to clear your config cache before installing new packages (including in your deployment pipelines).

**Closed as completed by driesvints** 2020-06-27 14:04 UTC
