### ISSUE TITLE
Blade helper renaming proposal

### ISSUE THREAD

**Issue by giovannipds** [driesvints/blade-icons#17] opened 2017-06-02 13:31 UTC
Hello.
I was thinking about the package, when we're talking about SVG (scalable vector graphics), not every SVG is an "icon", it could be just a simple graphic or whatever.
Perhaps shouldn't we consider renaming the helper `@icon` to `@svg`? Wouldn't it be better and more semantic flexible to the package? (I know we go the `svg_icon` as well, but my complaining is about the word "icon".
What do you guys thinks?
Cheers!

**Comment by adamwathan** [comment] 2017-06-02 14:07
Yeah not opposed to this, let's start with some aliases maybe?

**Comment by adamwathan** [comment] 2017-06-02 14:40
Just merged #18  which attempts to switch everything to SVG. Care to test our master and let me know if you run into any issues?

**Comment by giovannipds** [comment] 2017-06-05 04:38
@adamwathan not at all, I'll test it as soon as I can. I wasn't being able to use it because of something (as I've mentioned on the other issue #16).

**Comment by giovannipds** [comment] 2017-06-06 20:12
@adamwathan I'm testing it, seems to be working fine. =) I'm already using `@svg` (I'm using it with `inline` config set to `true`. Glad you were so receptive and helpful, thank you! o/

**Comment by giovannipds** [comment] 2017-06-07 11:57
@adamwathan phpunit tests are passing too.

**Comment by giovannipds** [comment] 2017-06-07 17:47
@adamwathan I think I may have found a bug. When using inline svgs, this happened:

    <svg class="C:\path\to\my\project svg svg-wine-mark" ...>
        ...
    </svg>

Where `svg` is my optional config `class` and `svg-wine-mark` is my inline svg's class. That `C:\path\to\my\project\` came out of nowhere. I've tested with the older version and this didn't happen. I'll be using the older version until there. Do you suspect where is that happening? Regards.

**Comment by adamwathan** [comment] 2017-06-07 17:50
Hmm just tried to replicate quickly but can't seem to. Can you create a repository that reproduces it and share it with me?

**Comment by giovannipds** [comment] 2017-06-07 19:22
@adamwathan Did you test it with the master branch (it doesn't happen on the release 0.1.1)?

**Comment by adamwathan** [comment] 2017-06-08 13:47
Yeah I tested it on master by adding a test that simulated what you described. Can you push a repository that reproduces it? That's the fastest way for me to diagnose without wasting time 👍

**Comment by LasseRafn** [comment] 2017-06-09 11:34
It's because **ALL** configs was mapped with `base_path` in `BladeSvgServiceProvider.php`. I've pushed a PR: #19

**Comment by giovannipds** [comment] 2017-06-21 20:16
Can we close the issue? =)

**Closed as completed** 2017-06-21 20:33 UTC
