### ISSUE TITLE
Prevent adding class if not specified a class

### ISSUE THREAD

**Issue by yaquawa** [driesvints/blade-icons#44] opened 2020-02-04 02:44 UTC
If the svg itself has the class attribute already. `svg_image('Foo')` will overwrite the original class attribute with an empty value. 

Thinking of a svg that can be used at multiple places, I have to specify the class name every time, which means it's hard to change when I want to change the class name of the svg, because I have to change all the args of the `svg_image` one by one.

**Comment by extrabright** [comment] 2020-03-26 17:26
Yep, that would be cool to add.

**Comment by driesvints** [comment] 2020-04-20 18:46
I'm not sure what the problem is. Do you mean that at the moment when you call `svg_image('Foo')` twice that the second outputted SVG doesn't has the `Foo` class? Can you try this with the next version branch? https://github.com/adamwathan/blade-svg/pull/50

**Comment by driesvints** [comment] 2020-04-26 14:53
Going to close this one. Feel free to provide feedback when you can.

**Comment by yaquawa** [comment] 2020-04-29 03:14
@driesvints 
I mean if I have a svg file like this:
```svg
<svg class="foobar">...</svg>
```

`svg_image('Foo')` will erase the original class attribute and bring me this:
```svg
<svg>...</svg>
```

**Comment by extrabright** [comment] 2020-04-29 05:04
@yaquawa is right. I have the same issue. I have an already applied class on the svg, but when I want to add new classes when using the injector you’ve build, it erases the original class.

**Comment by driesvints** [comment] 2020-04-29 08:41
I see. That could indeed be beneficial. I'll re-open this and leave it open for now. I don't think I'll get to this for the 0.4.0 release but maybe later on.

**Comment by davidhsianturi** [comment] 2020-06-20 14:35
@extrabright if you have already applied class on the SVG, i think you need to set default classes in the `config` file (in case you have the same value of class for all SVG) 
if not, the browser will always override this by passing an explicit class with your attributes.

**Comment by driesvints** [comment] 2021-02-10 08:36
I'm going to close this one as I don't think it's feasible to ever solve this in a clean way. It would mean the library would need to check every single icon for existing attributes. I think the direction I want to take the package more is to having icons not implement any attributes that aren't needed to "shape" the icon like class, id, etc. and let those be added through the package instead.

**Closed as completed by driesvints** 2021-02-10 08:36 UTC
Labels: enhancement
